dataset_name: all
num_train: 50000
num_valid: 500

density_loss: 0.01

train_batch_size: 10
valid_batch_size: 10
test_batch_size: 10

learning_rate: 1e-3
weight_decay: 0.0
num_epochs: 300
validation_interval: 10
use_gradient_clipping: true
clip_norm: 1.0
pin_memory: True
num_workers: 8
step_size: 10

num_bathes: 1000000
train_batch_interval: 100
validation_batch_interval: 500